sudo: required

git:
  depth: 3

services:
  - docker

install:
  - docker build --file Dockerfile.py3 --tag guillaume-florent/osvcad-py3:latest .
  - docker build --file Dockerfile.py2 --tag guillaume-florent/osvcad-py2:latest .

script:
  - docker run guillaume-florent/osvcad-py3:latest /bin/bash -c "cd /opt/osvcad;pytest tests/"
  - docker run guillaume-florent/osvcad-py2:latest /bin/bash -c "cd /opt/osvcad;pytest tests/"

after_script:
  - docker images